//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurTranslator1.WebBankService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebBankService.WebBankSoap")]
    public interface WebBankSoap {
        
        // CODEGEN: Generating message contract since element name ssn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffer", ReplyAction="*")]
        OurTranslator1.WebBankService.GetOfferResponse GetOffer(OurTranslator1.WebBankService.GetOfferRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOffer", ReplyAction="*")]
        System.Threading.Tasks.Task<OurTranslator1.WebBankService.GetOfferResponse> GetOfferAsync(OurTranslator1.WebBankService.GetOfferRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOfferRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOffer", Namespace="http://tempuri.org/", Order=0)]
        public OurTranslator1.WebBankService.GetOfferRequestBody Body;
        
        public GetOfferRequest() {
        }
        
        public GetOfferRequest(OurTranslator1.WebBankService.GetOfferRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOfferRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ssn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int creditScore;
        
        public GetOfferRequestBody() {
        }
        
        public GetOfferRequestBody(string ssn, int duration, int creditScore) {
            this.ssn = ssn;
            this.duration = duration;
            this.creditScore = creditScore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOfferResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOfferResponse", Namespace="http://tempuri.org/", Order=0)]
        public OurTranslator1.WebBankService.GetOfferResponseBody Body;
        
        public GetOfferResponse() {
        }
        
        public GetOfferResponse(OurTranslator1.WebBankService.GetOfferResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOfferResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOfferResult;
        
        public GetOfferResponseBody() {
        }
        
        public GetOfferResponseBody(string GetOfferResult) {
            this.GetOfferResult = GetOfferResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebBankSoapChannel : OurTranslator1.WebBankService.WebBankSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebBankSoapClient : System.ServiceModel.ClientBase<OurTranslator1.WebBankService.WebBankSoap>, OurTranslator1.WebBankService.WebBankSoap {
        
        public WebBankSoapClient() {
        }
        
        public WebBankSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebBankSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBankSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebBankSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OurTranslator1.WebBankService.GetOfferResponse OurTranslator1.WebBankService.WebBankSoap.GetOffer(OurTranslator1.WebBankService.GetOfferRequest request) {
            return base.Channel.GetOffer(request);
        }
        
        public string GetOffer(string ssn, int duration, int creditScore) {
            OurTranslator1.WebBankService.GetOfferRequest inValue = new OurTranslator1.WebBankService.GetOfferRequest();
            inValue.Body = new OurTranslator1.WebBankService.GetOfferRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.duration = duration;
            inValue.Body.creditScore = creditScore;
            OurTranslator1.WebBankService.GetOfferResponse retVal = ((OurTranslator1.WebBankService.WebBankSoap)(this)).GetOffer(inValue);
            return retVal.Body.GetOfferResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OurTranslator1.WebBankService.GetOfferResponse> OurTranslator1.WebBankService.WebBankSoap.GetOfferAsync(OurTranslator1.WebBankService.GetOfferRequest request) {
            return base.Channel.GetOfferAsync(request);
        }
        
        public System.Threading.Tasks.Task<OurTranslator1.WebBankService.GetOfferResponse> GetOfferAsync(string ssn, int duration, int creditScore) {
            OurTranslator1.WebBankService.GetOfferRequest inValue = new OurTranslator1.WebBankService.GetOfferRequest();
            inValue.Body = new OurTranslator1.WebBankService.GetOfferRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.duration = duration;
            inValue.Body.creditScore = creditScore;
            return ((OurTranslator1.WebBankService.WebBankSoap)(this)).GetOfferAsync(inValue);
        }
    }
}
