//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetBanks.RuleBaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RuleBaseService.RuleBaseServiceSoap")]
    public interface RuleBaseServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetBankQueuesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankQueues", ReplyAction="*")]
        GetBanks.RuleBaseService.GetBankQueuesResponse GetBankQueues(GetBanks.RuleBaseService.GetBankQueuesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBankQueues", ReplyAction="*")]
        System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBankQueuesResponse> GetBankQueuesAsync(GetBanks.RuleBaseService.GetBankQueuesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankQueuesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankQueues", Namespace="http://tempuri.org/", Order=0)]
        public GetBanks.RuleBaseService.GetBankQueuesRequestBody Body;
        
        public GetBankQueuesRequest() {
        }
        
        public GetBankQueuesRequest(GetBanks.RuleBaseService.GetBankQueuesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBankQueuesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Duration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CreditScore;
        
        public GetBankQueuesRequestBody() {
        }
        
        public GetBankQueuesRequestBody(double Amount, int Duration, int CreditScore) {
            this.Amount = Amount;
            this.Duration = Duration;
            this.CreditScore = CreditScore;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBankQueuesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBankQueuesResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetBanks.RuleBaseService.GetBankQueuesResponseBody Body;
        
        public GetBankQueuesResponse() {
        }
        
        public GetBankQueuesResponse(GetBanks.RuleBaseService.GetBankQueuesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBankQueuesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GetBanks.RuleBaseService.ArrayOfString GetBankQueuesResult;
        
        public GetBankQueuesResponseBody() {
        }
        
        public GetBankQueuesResponseBody(GetBanks.RuleBaseService.ArrayOfString GetBankQueuesResult) {
            this.GetBankQueuesResult = GetBankQueuesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RuleBaseServiceSoapChannel : GetBanks.RuleBaseService.RuleBaseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RuleBaseServiceSoapClient : System.ServiceModel.ClientBase<GetBanks.RuleBaseService.RuleBaseServiceSoap>, GetBanks.RuleBaseService.RuleBaseServiceSoap {
        
        public RuleBaseServiceSoapClient() {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RuleBaseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GetBanks.RuleBaseService.GetBankQueuesResponse GetBanks.RuleBaseService.RuleBaseServiceSoap.GetBankQueues(GetBanks.RuleBaseService.GetBankQueuesRequest request) {
            return base.Channel.GetBankQueues(request);
        }
        
        public GetBanks.RuleBaseService.ArrayOfString GetBankQueues(double Amount, int Duration, int CreditScore) {
            GetBanks.RuleBaseService.GetBankQueuesRequest inValue = new GetBanks.RuleBaseService.GetBankQueuesRequest();
            inValue.Body = new GetBanks.RuleBaseService.GetBankQueuesRequestBody();
            inValue.Body.Amount = Amount;
            inValue.Body.Duration = Duration;
            inValue.Body.CreditScore = CreditScore;
            GetBanks.RuleBaseService.GetBankQueuesResponse retVal = ((GetBanks.RuleBaseService.RuleBaseServiceSoap)(this)).GetBankQueues(inValue);
            return retVal.Body.GetBankQueuesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBankQueuesResponse> GetBanks.RuleBaseService.RuleBaseServiceSoap.GetBankQueuesAsync(GetBanks.RuleBaseService.GetBankQueuesRequest request) {
            return base.Channel.GetBankQueuesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GetBanks.RuleBaseService.GetBankQueuesResponse> GetBankQueuesAsync(double Amount, int Duration, int CreditScore) {
            GetBanks.RuleBaseService.GetBankQueuesRequest inValue = new GetBanks.RuleBaseService.GetBankQueuesRequest();
            inValue.Body = new GetBanks.RuleBaseService.GetBankQueuesRequestBody();
            inValue.Body.Amount = Amount;
            inValue.Body.Duration = Duration;
            inValue.Body.CreditScore = CreditScore;
            return ((GetBanks.RuleBaseService.RuleBaseServiceSoap)(this)).GetBankQueuesAsync(inValue);
        }
    }
}
