//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.LoanBrokerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoanBrokerService.LoanBrokerServiceSoap")]
    public interface LoanBrokerServiceSoap {
        
        // CODEGEN: Generating message contract since element name ssn from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeLoanBroker", ReplyAction="*")]
        Client.LoanBrokerService.InvokeLoanBrokerResponse InvokeLoanBroker(Client.LoanBrokerService.InvokeLoanBrokerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeLoanBroker", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.LoanBrokerService.InvokeLoanBrokerResponse> InvokeLoanBrokerAsync(Client.LoanBrokerService.InvokeLoanBrokerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeLoanBrokerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeLoanBroker", Namespace="http://tempuri.org/", Order=0)]
        public Client.LoanBrokerService.InvokeLoanBrokerRequestBody Body;
        
        public InvokeLoanBrokerRequest() {
        }
        
        public InvokeLoanBrokerRequest(Client.LoanBrokerService.InvokeLoanBrokerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeLoanBrokerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ssn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int duration;
        
        public InvokeLoanBrokerRequestBody() {
        }
        
        public InvokeLoanBrokerRequestBody(string ssn, double amount, int duration) {
            this.ssn = ssn;
            this.amount = amount;
            this.duration = duration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InvokeLoanBrokerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InvokeLoanBrokerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.LoanBrokerService.InvokeLoanBrokerResponseBody Body;
        
        public InvokeLoanBrokerResponse() {
        }
        
        public InvokeLoanBrokerResponse(Client.LoanBrokerService.InvokeLoanBrokerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InvokeLoanBrokerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InvokeLoanBrokerResult;
        
        public InvokeLoanBrokerResponseBody() {
        }
        
        public InvokeLoanBrokerResponseBody(string InvokeLoanBrokerResult) {
            this.InvokeLoanBrokerResult = InvokeLoanBrokerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoanBrokerServiceSoapChannel : Client.LoanBrokerService.LoanBrokerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanBrokerServiceSoapClient : System.ServiceModel.ClientBase<Client.LoanBrokerService.LoanBrokerServiceSoap>, Client.LoanBrokerService.LoanBrokerServiceSoap {
        
        public LoanBrokerServiceSoapClient() {
        }
        
        public LoanBrokerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanBrokerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanBrokerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanBrokerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.LoanBrokerService.InvokeLoanBrokerResponse Client.LoanBrokerService.LoanBrokerServiceSoap.InvokeLoanBroker(Client.LoanBrokerService.InvokeLoanBrokerRequest request) {
            return base.Channel.InvokeLoanBroker(request);
        }
        
        public string InvokeLoanBroker(string ssn, double amount, int duration) {
            Client.LoanBrokerService.InvokeLoanBrokerRequest inValue = new Client.LoanBrokerService.InvokeLoanBrokerRequest();
            inValue.Body = new Client.LoanBrokerService.InvokeLoanBrokerRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.amount = amount;
            inValue.Body.duration = duration;
            Client.LoanBrokerService.InvokeLoanBrokerResponse retVal = ((Client.LoanBrokerService.LoanBrokerServiceSoap)(this)).InvokeLoanBroker(inValue);
            return retVal.Body.InvokeLoanBrokerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.LoanBrokerService.InvokeLoanBrokerResponse> Client.LoanBrokerService.LoanBrokerServiceSoap.InvokeLoanBrokerAsync(Client.LoanBrokerService.InvokeLoanBrokerRequest request) {
            return base.Channel.InvokeLoanBrokerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.LoanBrokerService.InvokeLoanBrokerResponse> InvokeLoanBrokerAsync(string ssn, double amount, int duration) {
            Client.LoanBrokerService.InvokeLoanBrokerRequest inValue = new Client.LoanBrokerService.InvokeLoanBrokerRequest();
            inValue.Body = new Client.LoanBrokerService.InvokeLoanBrokerRequestBody();
            inValue.Body.ssn = ssn;
            inValue.Body.amount = amount;
            inValue.Body.duration = duration;
            return ((Client.LoanBrokerService.LoanBrokerServiceSoap)(this)).InvokeLoanBrokerAsync(inValue);
        }
    }
}
